### ISSUE TITLE
Add CEL support to conditionField selector

### ISSUE THREAD

**Issue by achetronic** [prosimcorp/searchruler#6]
Hi there!

Currently, the operator use GJson for selecting fields from the query result in `SearchRule` resource. Basically this is not powerful enough. It would be awesome to support something better like CEL

Something as follows:

```yaml
queryJSON: >
    {
      "aggs": {},
      "_source": {
        "excludes": []
      },
      "query": {
        "bool": {
          "must": [],
          "filter": [
            {
              "bool": {
                "should": [
                  {
                    "range": {
                      "status": {
                        "gte": "399"
                      }
                    }
                  }
                ],
                "minimum_should_match": 1
              }
            },
            {
              "range": {
                "timestamp": {
                  "format": "strict_date_optional_time",
                  "gte": "now-15m",
                  "lte": "now"
                }
              }
            },
            {
              "range": {
                "status": {
                  "gte": "399"
                }
              }
            }
          ]
        }
      },
      "fields": [
        {
          "field": "timestamp",
          "format": "date_time"
        }
      ]
    }


# THIS WILL RETURN: 2
celConditionField: |
  {
    "503": hits.hits.map(m, m._source.status).filter(x, x == 503).size(),
    "504": hits.hits.map(m, m._source.status).filter(x, x == 504).size()
  }["503"]


condition:
  operator: "greaterThan"
  threshold: "100"
  for: "1m"
```

The response from elastic could be:

```yaml
{
  "took": 138,
  "timed_out": false,
  "_shards": {
    "total": 21,
    "successful": 21,
    "skipped": 18,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 2,
      "relation": "eq"
    },
    "max_score": 0,
    "hits": [
      {
        "_index": "[redacted]",
        "_id": "[redacted]",
        "_score": 0,
        "_source": {
          "timestamp": "2024-12-11T15:37:02Z",
          "pod_name": "[redacted]",
          "namespace": "[redacted]",
          "level": "info",
          "msg": "response",
          "content-length": "285",
          "content-type": "text/html; charset=utf-8",
          "x-varnish": "",
          "x-cache-hit": "MISS",
          "via": "1.1 varnish-0 (Varnish/7.5)",
          "request-id": "[redacted]",
          "hashkey": "[redacted]",
          "backend": "[redacted]",
          "status": 503,
          "duration_f": 0,
          "upstream_connect_time_f": 0,
          "upstream_header_time_f": 0,
          "upstream_response_time_f": 0,
          "connection_time_f": 0
        },
        "fields": {
          "timestamp": [
            "2024-12-11T15:37:02.000Z"
          ]
        }
      },
      {
        "_index": "[redacted]",
        "_id": "[redacted]",
        "_score": 0,
        "_source": {
          "timestamp": "2024-12-11T15:37:02Z",
          "pod_name": "[redacted]",
          "namespace": "[redacted]",
          "level": "info",
          "msg": "response",
          "content-length": "285",
          "content-type": "text/html; charset=utf-8",
          "x-varnish": "",
          "x-cache-hit": "MISS",
          "via": "1.1 varnish-0 (Varnish/7.5)",
          "request-id": "[redacted]",
          "hashkey": "[redacted]",
          "backend": "[redacted]",
          "status": 503,
          "duration_f": 0,
          "upstream_connect_time_f": 0,
          "upstream_header_time_f": 0,
          "upstream_response_time_f": 0,
          "connection_time_f": 0
        },
        "fields": {
          "timestamp": [
            "2024-12-11T15:37:02.000Z"
          ]
        }
      }
    ]
  }
}

```

What do you think? I think this is much more powerful and handy than GJson for complex use cases as I described
